name: Create Shiny User Auth0 

on:
  workflow_dispatch:
    inputs:
      responder:
        description: 'Responder'
        required: true
        type: string
      email:
        description: 'Email'
        required: true
        type: string
      dashes:
        description: 'Dashes'
        required: true
        type: string

jobs:
  create-user:
    name: Create Auth0 User and Send Email
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r auth0/requirements.txt

      - name: Create Auth0 Shiny User
        env:
          EMAIL: ${{ github.event.inputs.email }}
          DASHES: ${{ github.event.inputs.dashes }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          OUTPUT=$(python auth0/create.py)

          PASSWORD=$(echo "$OUTPUT" | grep "PASSWORD=" | cut -d'=' -f2)
          STATUS=$(echo "$OUTPUT" | grep "STATUS=" | cut -d'=' -f2)
          echo "SCRIPT_PASSWORD=$PASSWORD" >> "$GITHUB_ENV"
          echo "SCRIPT_STATUS=$STATUS" >> "$GITHUB_ENV"

      - name: Send Email to User
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_FOR: ${{ github.event.inputs.email }}
          RESPONDER: ${{ github.event.inputs.responder }}
          PASSWORD: ${{ env.PASSWORD }}
          SHINY_URL: ${{ secrets.SHINY_URL }}
          STATUS: ${{ secrets.STATUS }}
        run: |
          python auth0/send_email.py
