name: Create Shiny User Auth0 

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email'
        required: true
        type: string
      dashes:
        description: 'Dashes'
        required: true
        type: string

jobs:
  print-form-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r auth0/requirements.txt

      - name: Executar script Python
        env:
          EMAIL: ${{ github.event.inputs.email }}
          DASHES: ${{ github.event.inputs.dashes }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          python auth0/create.py