name: Create Shiny User Auth0 

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email'
        required: true
        type: string
      dashes:
        description: 'Dashes'
        required: true
        type: string

jobs:
  create-user:
    name: Create Auth0 User and Send Email
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Auth0 Shiny User
        env:
          EMAIL: ${{ github.event.inputs.email }}
          DASHES: ${{ github.event.inputs.dashes }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          PASSWORD=$(python create.py)
          echo "USER_PASSWORD=$PASSWORD" >> "$GITHUB_ENV"

      - name: Send Email to User
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ github.event.inputs.email }}
          PASSWORD: ${{ env.USER_PASSWORD }}
        run: |
          python send_email.py